site_name: ecv-wiki
repo_name: ECV-Lab-KULeuven/ECV-Lab-KULeuven.github.io
repo_url: https://github.com/ECV-Lab-KULeuven/ECV-Lab-KULeuven.github.io
site_url: https://ecv-lab-kuleuven.github.io/

nav:
    - Home: index.md
    - Recently edited:
            - singularity.md
            - docker.md
            - index.md
            - template.md
    - Pages:
          - ...

theme:
    name: material
    favicon: images/ECV-cutout.png
    logo: images/ECV-cutout.png
    palette:
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
              icon: material/weather-night
              name: Switch to system preference
    font:
        text: "Lora"
        code: "Ubuntu Mono"
    features:
        - announce.dismiss
        - content.action.edit
        - content.code.annotate
        - content.code.copy
        - navigation.instant
        - navigation.sections
        - navigation.prune
        - navigation.top
        - navigation.tracking
        - search.share
        - search.suggest
        - search.highlight
        - toc.follow

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - admonition
    - attr_list
    - def_list
    - tables
    - md_in_html
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.critic
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.details
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.arithmatex:
          generic: true
plugins:
    - search
    - git-authors:
          show_contribution: true
          sort_authors_by: contribution
          exclude:
              - index.md
    - git-revision-date-localized:
          type: timeago
    - git-latest-changes:
          limit_to_docs_dir: True
          repo_vendor: github
    - awesome-pages

extra:
    generator: false
    social:
        - icon: fontawesome/brands/x-twitter
          link: https://twitter.com/LemeyLab
        - icon: fontawesome/brands/github
          link: https://github.com/ECV-Lab-KULeuven
